-- moment.TB_MEMBER definition
CREATE TABLE TB_MEMBER (
  MEMBER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BIRTH DATE DEFAULT NULL,
  PROFILE_IMAGE_URL VARCHAR(255) DEFAULT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  CONNECTION_USER_CODE VARCHAR(255) DEFAULT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  NAME VARCHAR(255) DEFAULT NULL,
  PASSWORD VARCHAR(255) DEFAULT NULL,
  PHONE_NUMBER VARCHAR(255) DEFAULT NULL,
  PROVIDER VARCHAR(255) DEFAULT NULL,
  PROVIDER_ID VARCHAR(255) DEFAULT NULL,
  REFRESH_TOKEN VARCHAR(255) DEFAULT NULL,
  USER_CODE VARCHAR(255) DEFAULT NULL,
  COUPLE_ID BIGINT DEFAULT NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  GENDER VARCHAR(10) DEFAULT NULL, -- ENUM 대체
  ROLE VARCHAR(10) DEFAULT NULL -- ENUM 대체
);

-- moment.TB_COUPLE definition
CREATE TABLE TB_COUPLE (
  COUPLE_ID bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MEETING_DATE date DEFAULT NULL,
  CREATED_AT datetime(6) NOT NULL,
  UPDATED_AT datetime(6) NOT NULL,
  IS_DELETED BOOLEAN NOT NULL
);